### ISSUE TITLE
Fix failing tests cases in python 2.7

### ISSUE THREAD

**Issue by kylegibson** [PolicyStat/htmltreediff#10]
htmltreediff is configured to run tests against python 2.6, and there are several failing tests in python 2.7. Updated the tox config to run python 2.7 and fix all the failing tests.

**Comment by bocribbz** [comment]
Any reason why `lxml` is not in testing requirements?

**Comment by bocribbz** [comment]
The issue with py27 tests seems to be related to xml handling.
It seems like the py26 version is altering the xml data.
eg. 
```<name>Foo Bar</name>```
becomes 
```<name>
    Foo Bar
</name>```
So name is no longer `Foo Bar` but it is `    Foo Bar` (4 extra spaces).
This got fixed somewhere in py27.

**Comment by bocribbz** [comment]
I think the options are:
* drop support for py26
* monkey patch py26's minidom writexml http://ronrothman.com/public/leftbraned/xml-dom-minidom-toprettyxml-and-silly-whitespace/ (solution number 3)
* rewrite the lib to use lxml if possible

**Comment by jlward** [comment]
Handled in #15
